Controllers/AssetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Gmt_Asset_Tracker.Data;
using Gmt_Asset_Tracker.Models;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Microsoft.AspNetCore.Http;
using OfficeOpenXml.FormulaParsing.Excel.Functions.Math;
using Gmt_Asset_Tracker.ViewModels;
using Microsoft.Extensions.Hosting;
using System.Net;
using System.Drawing.Printing;
using Microsoft.AspNetCore.Authorization;
using ClosedXML.Excel;
using DocumentFormat.OpenXml.Wordprocessing;

//using System.Net.Mail;
using MimeKit;
using MailKit.Net.Smtp;
using DocumentFormat.OpenXml.Bibliography;
using System.Security.Policy;

namespace Gmt_Asset_Tracker.Controllers
{
	[Authorize]
	public class AssetController : Controller
	{
		private readonly AssetTrackerContext _context;
		private readonly IWebHostEnvironment _webHostEnvironment;

		public AssetController(AssetTrackerContext context, IWebHostEnvironment webHostEnvironment)
		{
			_context = context;
			_webHostEnvironment = webHostEnvironment;
		}

		// GET: Asset
		public async Task<IActionResult> Index()
		{
			//int pagesize = 2;
			var assets = _context.Assets.Include(a => a.Asset_State)
				.Include(a => a.Category)
				.Include(a => a.Department)
				.Include(a => a.Location)
				.Include(a => a.Present_location)
				.Include(a => a.Vendor)
				.Include(a => a.Physical_check)
				.OrderByDescending(p => p.Delivery_date);
			//.Skip((p - 1) * pagesize)
			//.Take(pagesize);

			ViewData["Assets"] = _context.Assets.Count();
			ViewData["Vendors"] = _context.Vendors.Count();
			ViewData["Departments"] = _context.Departments.Count();
			ViewData["Locations"] = _context.Locations.Count();

			//ViewBag.PageNumber = p;
			//ViewBag.PageRange = pagesize;
			//ViewBag.TotalPages = (int)Math.Ceiling((decimal)_context.Assets.Count() / pagesize);

			//var assetTrackerContext = _context.Assets.Include(a => a.Asset_State).Include(a => a.Category).Include(a => a.Department).Include(a => a.Location).Include(a => a.Present_location).Include(a => a.Vendor);
			return View(await assets.ToListAsync());
		}

		public async Task<IActionResult> nullassettag()
		{
			var assets = _context.Assets.Include(a => a.Asset_State)
				.Include(a => a.Category)
				.Include(a => a.Department)
				.Include(a => a.Location)
				.Include(a => a.Present_location)
				.Include(a => a.Vendor)
				.Include(a => a.Physical_check)
				.OrderByDescending(p => p.Delivery_date).Where(x => x.Asset_tag == null);

			return View(await assets.ToListAsync());
		}

		public IActionResult Email()
		{
			var assets = _context.Assets.Include(a => a.Asset_State)
				.Include(a => a.Category)
				.Include(a => a.Department)
				.Include(a => a.Location)
				.Include(a => a.Present_location)
				.Include(a => a.Vendor)
				.Include(a => a.Physical_check)
				.OrderByDescending(p => p.Delivery_date).Where(x => x.Asset_tag == null);

			//ViewData["url"] = url;

			//var message = new MimeMessage();
			//message.From.Add(new MailboxAddress("GMT Vendor Evaluation", "Auto.Mail@gmt-limited.com"));
			//message.To.Add(new MailboxAddress(departmentinfo.email));
			//message.Subject = "GMT Vendor Evaluation Evaluation";
			//message.Body = new BodyBuilder { HtmlBody = string.Format("<h3 style='color:black;'>Click on the link below to Evaluate this Product/Service({0}) delivered to your Department <hr /> {1}</h3>", productname, url) }.ToMessageBody();

			//using (var client = new SmtpClient())
			//{
			//    client.Connect("smtp.office365.com", 587, false);
			//    client.Authenticate("Auto.Mail@gmt-limited.com", "Hav!34iT");

			//    client.Send(message);
			//    client.Disconnect(true);
			//}

			//var message = new MimeMessage();
			//message.From.Add(new MailboxAddress("GMT Vendor Evaluation", "fisayo.adegun@gmt-limited.com"));
			//message.To.Add(new MailboxAddress("i_zzyfizzy@live.com"));
			//message.Subject = "GMT Vendor Evaluation Evaluation";
			//message.Body = new BodyBuilder { HtmlBody = string.Format("<h3 style='color:black;'>Click on the link below to Evaluate this Product/Service({0}) delivered to your Department <hr /> {1}</h3>") }.ToMessageBody();

			//using (var client = new SmtpClient())
			//{
			//	client.Connect("smtp.office365.com", 587, false);
			//	client.Authenticate("fisayo.adegun@gmt-limited.com", "Surulere007");

			//	client.Send(message);
			//	client.Disconnect(true);
			//}
			return View();
		}

		// GET: Asset/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var asset = await _context.Assets
				.Include(a => a.Asset_State)
				.Include(a => a.Category)
				.Include(a => a.Department)
				.Include(a => a.Location)
				.Include(a => a.Physical_check)
				.Include(a => a.Present_location)
				.Include(a => a.Vendor)
				.FirstOrDefaultAsync(m => m.Id == id);
			if (asset == null)
			{
				return NotFound();
			}

			return View(asset);
		}

		// GET: Asset/Create
		public IActionResult Create()
		{
			ViewData["AssetStateId"] = new SelectList(_context.Asset_States, "Id", "Asset_state");
			ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Category_name");
			ViewData["DepartmentId"] = new SelectList(_context.Departments, "Id", "Department_name");
			ViewData["LocationId"] = new SelectList(_context.Locations, "Id", "Location_name");
			ViewData["CheckId"] = new SelectList(_context.Physical_Checks, "Id", "Check_name");
			ViewData["PresentLocationId"] = new SelectList(_context.Locations, "Id", "Location_name");
			ViewData["VendorId"] = new SelectList(_context.Vendors, "Id", "Vendor_name");
			return View();
		}

		// POST: Asset/Create
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create(int? id, [FromServices] IWebHostEnvironment hostingEnvironment, Asset asset)
		{
			if (ModelState.IsValid)
			{
				var assettag = await _context.Assets.FirstOrDefaultAsync(x => x.Asset_tag == asset.Asset_tag);
				if (assettag != null && asset.Asset_tag != null)
				{
					ModelState.AddModelError("", "An asset with this asset tag already exists.");
					return View(asset);
				}
				var servicetag = await _context.Assets.FirstOrDefaultAsync(x => x.Service_tag == asset.Service_tag);
				if (servicetag != null)
				{
					ModelState.AddModelError("", "An asset with this service tag already exists");
					return View(asset);
				}
				string imageName = "noimage.png";
				if (asset.ImageUpload != null)
				{
					string folder = "media/images/";
					imageName = Guid.NewGuid().ToString() + "_" + asset.ImageUpload.FileName;
					string serverFolder = Path.Combine(_webHostEnvironment.WebRootPath, folder, imageName);

					await asset.ImageUpload.CopyToAsync(new FileStream(serverFolder, FileMode.Create));
				}

				string pdffile = "norequisitionpack.pdf";
				if (asset.RequistionpackUpload != null)
				{
					string fileName = $"{hostingEnvironment.WebRootPath}\\media\\pdfs\\{asset.RequistionpackUpload.FileName}";

					pdffile = asset.RequistionpackUpload.FileName;
					using (FileStream fileStream = System.IO.File.Create(fileName))
					{
						asset.RequistionpackUpload.CopyTo(fileStream);
						fileStream.Flush();
					}
				}
				asset.Requistion_pack = pdffile;
				asset.Image = imageName;

				_context.Add(asset);
				await _context.SaveChangesAsync();

				TempData["Success"] = "The Asset has been added";
				return RedirectToAction(nameof(Index));
			}
			ViewData["AssetStateId"] = new SelectList(_context.Asset_States, "Id", "Asset_state");
			ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Category_name");
			ViewData["DepartmentId"] = new SelectList(_context.Departments, "Id", "Department_name");
			ViewData["LocationId"] = new SelectList(_context.Locations, "Id", "Location_name");
			ViewData["CheckId"] = new SelectList(_context.Physical_Checks, "Id", "Check_name");
			ViewData["PresentLocationId"] = new SelectList(_context.Locations, "Id", "Location_name");
			ViewBag.VendorId = new SelectList(_context.Vendors, "Id", "Vendor_name", asset.VendorId);
			return View(asset);
		}

		// GET: Asset/Edit/5
		public async Task<IActionResult> Edit(int? id)
		{
			Asset asset = await _context.Assets.FindAsync(id);
			if (id == null)
			{
				return NotFound();
			}

			ViewData["AssetStateId"] = new SelectList(_context.Asset_States, "Id", "Asset_state", asset.AssetStateId);
			ViewBag.CategoryId = new SelectList(_context.Categories, "Id", "Category_name", asset.CategoryId);
			ViewData["DepartmentId"] = new SelectList(_context.Departments, "Id", "Department_name", asset.DepartmentId);
			ViewData["LocationId"] = new SelectList(_context.Locations, "Id", "Location_name", asset.LocationId);
			ViewData["CheckId"] = new SelectList(_context.Physical_Checks, "Id", "Check_name", asset.CheckId);
			ViewData["PresentLocationId"] = new SelectList(_context.Locations, "Id", "Location_name", asset.PresentLocationId);
			//ViewData["VendorId"] = new SelectList(_context.Vendors, "Id", "Vendor_name", asset.VendorId);
			ViewBag.VendorId = new SelectList(_context.Vendors, "Id", "Vendor_name", asset.VendorId);
			return View(asset);
		}

		// POST: Asset/Edit/5
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [FromServices] IWebHostEnvironment hostingEnvironment, Asset asset)
		{
			//if (id != asset.Id)
			//{
			//	return NotFound();
			//}
			ViewBag.CategoryId = new SelectList(_context.Categories, "Id", "Category_name", asset.CategoryId);

Controllers/LocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Gmt_Asset_Tracker.Data;
using Gmt_Asset_Tracker.Models;
using Microsoft.AspNetCore.Authorization;

namespace Gmt_Asset_Tracker.Controllers
{
	[Authorize]
	public class LocationController : Controller
	{
		private readonly AssetTrackerContext _context;

		public LocationController(AssetTrackerContext context)
		{
			_context = context;
		}

		// GET: Location
		public async Task<IActionResult> Index()
		{
			return View(await _context.Locations.ToListAsync());
		}

		// GET: Location/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var location = await _context.Locations
				.FirstOrDefaultAsync(m => m.Id == id);
			if (location == null)
			{
				return NotFound();
			}

			return View(location);
		}

		// GET: Location/Create
		public IActionResult Create()
		{
			return View();
		}

		// POST: Location/Create
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Id,Location_name")] Location location)
		{
			if (ModelState.IsValid)
			{
				_context.Add(location);
				await _context.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}
			return View(location);
		}

		// GET: Location/Edit/5
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var location = await _context.Locations.FindAsync(id);
			if (location == null)
			{
				return NotFound();
			}
			return View(location);
		}

		// POST: Location/Edit/5
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("Id,Location_name")] Location location)
		{
			if (id != location.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(location);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!LocationExists(location.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			return View(location);
		}

		// GET: Location/Delete/5
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var location = await _context.Locations
				.FirstOrDefaultAsync(m => m.Id == id);
			if (location == null)
			{
				return NotFound();
			}

			return View(location);
		}

		// POST: Location/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			var location = await _context.Locations.FindAsync(id);
			_context.Locations.Remove(location);
			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}

		private bool LocationExists(int id)
		{
			return _context.Locations.Any(e => e.Id == id);
		}
	}
}

Controllers/VendorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Gmt_Asset_Tracker.Data;
using Gmt_Asset_Tracker.Models;
using Microsoft.AspNetCore.Authorization;

namespace Gmt_Asset_Tracker.Controllers
{
	[Authorize]
	public class VendorController : Controller
	{
		private readonly AssetTrackerContext _context;

		public VendorController(AssetTrackerContext context)
		{
			_context = context;
		}

		// GET: Vendor
		public async Task<IActionResult> Index()
		{
			return View(await _context.Vendors.ToListAsync());
		}

		// GET: Vendor/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var vendor = await _context.Vendors
				.FirstOrDefaultAsync(m => m.Id == id);
			if (vendor == null)
			{
				return NotFound();
			}

			return View(vendor);
		}

		// GET: Vendor/Create
		public IActionResult Create()
		{
			return View();
		}

		// POST: Vendor/Create
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Id,Vendor_name")] Vendor vendor)
		{
			if (ModelState.IsValid)
			{
				_context.Add(vendor);
				await _context.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}
			return View(vendor);
		}

		// GET: Vendor/Edit/5
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var vendor = await _context.Vendors.FindAsync(id);
			if (vendor == null)
			{
				return NotFound();
			}
			return View(vendor);
		}

		// POST: Vendor/Edit/5
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("Id,Vendor_name")] Vendor vendor)
		{
			if (id != vendor.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(vendor);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!VendorExists(vendor.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			return View(vendor);
		}

		// GET: Vendor/Delete/5
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var vendor = await _context.Vendors
				.FirstOrDefaultAsync(m => m.Id == id);
			if (vendor == null)
			{
				return NotFound();
			}

			return View(vendor);
		}

		// POST: Vendor/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			var vendor = await _context.Vendors.FindAsync(id);
			_context.Vendors.Remove(vendor);
			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}

		private bool VendorExists(int id)
		{
			return _context.Vendors.Any(e => e.Id == id);
		}
	}
}

Views/Shared/_AuthenticationLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] GMT Asset Tracker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a href="#" class="navbar-brand"><img src="/media/logo/logo.PNG" width="40" height="50"></a>
                <a class="navbar-brand" asp-area="" asp-controller="Asset" asp-action="Index">GMT Asset Tracker</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                    </ul>
                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1" style="float:right;">
                        <li>
                            <partial name="_LoginPartial" />
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="bg-image">
        @*<img src="/media/rhemalogo2.jpg" />*@
    </div>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <span id="current-year"></span> - GMT Asset Tracker
        </div>
    </footer>
    <script>
        document.getElementById("current-year").innerHTML = new Date().getFullYear();
    </script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" >

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gmt Asset Tracker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="~/lib/fontawesome-iconpicker/css/fontawesome-iconpicker.css" rel="stylesheet" />
    <link href="~/lib/fontawesome-iconpicker/css/fontawesome-iconpicker.min.css" />

    <link type="text/css" rel="stylesheet" href="~/css/jquery.dataTables.css" />
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
</head>
<body>
    <header>
        <nav class="navbar sticky-top navbar-expand-md navbar-dark bg-dark" id="NSNavbar">
            <div class="container d-flex flex-column flex-md-row justify-content-between">
                <!-- Brand -->
                <div class="navbar-header">
                   
                    <a href="#" class="navbar-brand" style="background-color:azure; border-radius:20px;"><img src="/media/logo/logo.PNG" alt="Logo" style="width:40px; height:40px;"></a>
                    <a class="navbar-brand" asp-area="" asp-controller="Asset" asp-action="Index">GMT Asset Tracker</a>
                </div>

                <!-- Toggler/collapsibe Button -->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar" aria-controls="collapsibleNavbar" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Navbar links -->
                <div class="collapse navbar-collapse" id="collapsibleNavbar">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Asset" asp-action="Index">Home<span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Vendor" asp-action="Index">Vendors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Location" asp-action="Index">Locations</a>
                        </li>
                        <li class="nav-item">
                            <div class="dropdown">
                                <button class="dropbtn" onclick="myFunction1()" style="color:aqua;">
                                    Menu
                                    <i class="fa fa-caret-down"></i>
                                </button>
                                <div class="dropdown-content" id="myDropdown">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Physical_check" asp-action="Index">Physical Check</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Asset_State" asp-action="Index">Asset States</a>
                                </div>
                            </div>
                        </li>
                    </ul>
                    <ul style="float:right;">

                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>

        @*<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3" style="width:100%; height:100px;">
            <div class="container" style="width:100%">
                <a href="#" class="navbar-brand"><img src="/media/logo/logo.PNG" width="40" height="50"></a>
                <a class="navbar-brand" asp-area="" asp-controller="Asset" asp-action="Index">GMT Asset Tracker</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">

                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Asset" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vendor" asp-action="Index">Vendors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Location" asp-action="Index">Locations</a>
                        </li>
                        <li class="nav-item">
                            <div class="dropdown">
                                <button class="dropbtn" onclick="myFunction1()">
                                    Menu
                                    <i class="fa fa-caret-down"></i>
                                </button>
                                <div class="dropdown-content" id="myDropdown">
                                    <a asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
                                    <a asp-area="" asp-controller="Physical_check" asp-action="Index">Physical Check</a>
                                    <a asp-area="" asp-controller="Asset_State" asp-action="Index">Asset States</a>
                                </div>
                            </div>
                        </li>
                    </ul>

                    <ul style="float:right;">

                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>*@
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_NotificationPartial" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <span id="current-year"></span> - Gmt Asset Tracker  <a asp-area="" asp-controller="Home" asp-action="Privacy"></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jqueryui/jquery-ui.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/fontawesome-iconpicker/js/fontawesome-iconpicker.js"></script>
    <script src="~/lib/fontawesome-iconpicker/js/fontawesome-iconpicker.min.js"></script>
    <script type="text/javascript" charset="utf8" src="~/js/jquery.dataTables.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
    <script>
        document.getElementById("current-year").innerHTML = new Date().getFullYear();
        $(document).ready(function () {
            $('#table_id').DataTable();
        });
        /* When the user clicks on the button,
       toggle between hiding and showing the dropdown content */
        function myFunction1() {
            document.getElementById("myDropdown").classList.toggle("show");
        }
        // Close the dropdown if the user clicks outside of it
        window.onclick = function (e) {
            if (!e.target.matches('.dropbtn')) {
                var myDropdown = document.getElementById("myDropdown");
                if (myDropdown.classList.contains('show')) {
                    myDropdown.classList.remove('show');
                }
            }
        }

        function myFunction() {

            // Declare variables
            var input = document.getElementById("myInput");
            var filter = input.value.toUpperCase();
            var table = document.getElementById("myTable");
            var trs = table.tBodies[0].getElementsByTagName("tr");

            // Loop through first tbody's rows
            for (var i = 0; i < trs.length; i++) {

                // define the row's cells
                var tds = trs[i].getElementsByTagName("td");

                // hide the row
                trs[i].style.display = "none";

                // loop through row cells
                for (var i2 = 0; i2 < tds.length; i2++) {

                    // if there's a match
                    if (tds[i2].innerHTML.toUpperCase().indexOf(filter) > -1) {

                        // show the row
                        trs[i].style.display = "";

                        // skip to the next row
                        continue;

                    }
                }
            }

        }
        $(document).ready(function () {
            $('#myTable').DataTable({
                "paging": true // false to disable pagination (or any other option)
            });
            $('.dataTables_length').addClass('bs-select');
        });
    </script>
</body>
</html>

Views/Shared/_NotificationPartial.cshtml
@if (TempData["Success"] != null)
{
    <div class="alert alert-success notification">
        @TempData["Success"]
    </div>
}

@if (TempData["Error"] != null)
{
    <div class="alert alert-danger notification">
        @TempData["Error"]
    </div>
}